/**
 * HireFlow Deterministic ATS Scoring Engine
 * ──────────────────────────────────────────
 * Core Principles:
 * 1. The ATS score is NEVER generated by Gemini. It is calculated by deterministic application rules.
 * 2. Same input analyzed twice MUST return the exact same score (0% randomness).
 * 3. Every point corresponds to a real rule with transparent max scores totaling 100 points.
 * 4. General ATS Compatibility and Job Description Match are kept completely separate.
 * 5. Term normalization resolves React / React.js / ReactJS, JS / JavaScript, etc.
 * 6. Resume-type aware: 'fresher' vs 'experienced' scoring logic.
 */

import type {
  ParsedResumeData,
  ATSCategoryKey,
  ATSCategoryResult,
  ATSFullReport,
  ATSPriority,
  ATSRuleResult,
  RuleSeverity,
  JDMatchBreakdown,
  CategorizedMissingKeyword,
  ResumeType,
} from '../types';
import rulesConfig from '../data/atsRules.json';

// ─── Term Normalization Engine ────────────────────────────────────────────────

const SYNONYM_MAP: Record<string, string[]> = (rulesConfig as any).synonymTerms || {
  react: ['react.js', 'reactjs', 'react 18', 'react native'],
  javascript: ['js', 'es6', 'ecmascript'],
  typescript: ['ts'],
  'node.js': ['node', 'nodejs', 'node js'],
  python: ['py', 'python3'],
  postgresql: ['postgres', 'pgsql'],
  aws: ['amazon web services', 'amazon cloud'],
  gcp: ['google cloud platform', 'google cloud'],
  azure: ['microsoft azure'],
  docker: ['containers', 'containerization', 'docker container'],
  kubernetes: ['k8s'],
  'ci/cd': ['cicd', 'continuous integration', 'github actions', 'gitlab ci', 'jenkins'],
  'rest api': ['rest', 'restful', 'restful api', 'restful apis'],
  'tailwind css': ['tailwind', 'tailwindcss'],
  css: ['css3', 'scss', 'sass'],
  html: ['html5'],
  express: ['express.js', 'expressjs'],
  vue: ['vue.js', 'vuejs'],
  angular: ['angular.js', 'angularjs'],
  'next.js': ['next', 'nextjs'],
};

/**
 * Normalizes a technical term to its canonical representation.
 * E.g. "React.js" -> "react", "JS" -> "javascript", "Postgres" -> "postgresql"
 */
export function normalizeTerm(term: string): string {
  const clean = term.trim().toLowerCase();
  for (const [canonical, aliases] of Object.entries(SYNONYM_MAP)) {
    if (clean === canonical || aliases.map(a => a.toLowerCase()).includes(clean)) {
      return canonical;
    }
  }
  return clean;
}

/**
 * Checks if two terms match, taking normalization into account.
 */
export function areTermsEquivalent(termA: string, termB: string): boolean {
  if (!termA || !termB) return false;
  const normA = normalizeTerm(termA);
  const normB = normalizeTerm(termB);
  if (normA === normB) return true;

  // Check if one contains the other
  if (normA.length >= 4 && normB.length >= 4) {
    return normA.includes(normB) || normB.includes(normA);
  }
  return false;
}

/**
 * Checks if a normalized target term exists in text.
 */
export function textContainsTerm(text: string, term: string): boolean {
  if (!text || !term) return false;
  const textLower = text.toLowerCase();
  const normTarget = normalizeTerm(term);

  // Check exact canonical string
  if (textLower.includes(normTarget)) return true;

  // Check all aliases
  const aliases = SYNONYM_MAP[normTarget] || [];
  for (const alias of aliases) {
    const escaped = alias.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'i');
    if (regex.test(textLower)) return true;
  }

  // Regex boundary match for target
  const escapedTarget = normTarget.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`\\b${escapedTarget}\\b`, 'i').test(textLower);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function clamp(val: number, min = 0, max = 100): number {
  return Math.min(max, Math.max(min, val));
}

function getResumeText(r: ParsedResumeData): string {
  const parts: string[] = [];

  if (r.personalInfo) {
    const pi = r.personalInfo;
    if (pi.fullName) parts.push(pi.fullName);
    if (pi.jobTitle) parts.push(pi.jobTitle);
    if (pi.summary) parts.push(pi.summary);
  }

  if (r.experiences?.length) {
    r.experiences.forEach((e) => {
      parts.push(e.title || '');
      parts.push(e.company || '');
      parts.push(e.period || '');
      (e.bullets || []).forEach((b) => parts.push(b));
    });
  }

  if (r.education?.length) {
    r.education.forEach((ed) => {
      parts.push(ed.degree || '');
      parts.push(ed.institution || '');
      parts.push(ed.period || '');
    });
  }

  if (r.skills) parts.push(r.skills);

  if (r.projects?.length) {
    r.projects.forEach((p) => {
      parts.push(p.title || '');
      parts.push(p.description || '');
      (p.bullets || []).forEach((b) => parts.push(b));
      (p.techStack || []).forEach((t) => parts.push(t));
    });
  }

  if (r.certificates?.length) {
    r.certificates.forEach((c) => {
      parts.push(c.title || '');
      parts.push(c.issuer || '');
    });
  }

  return parts.join(' ');
}

function getAllBullets(r: ParsedResumeData): string[] {
  const bullets: string[] = [];
  (r.experiences || []).forEach((e) => bullets.push(...(e.bullets || [])));
  (r.projects || []).forEach((p) => bullets.push(...(p.bullets || [])));
  return bullets;
}

// ─── Deterministic Rule Evaluation ───────────────────────────────────────────

function createRuleResult(
  id: string,
  category: string,
  severity: RuleSeverity,
  passed: boolean,
  score: number,
  maxScore: number,
  message: string,
  recommendation: string | null
): ATSRuleResult {
  return {
    id,
    category,
    severity,
    passed,
    score: Math.min(maxScore, Math.max(0, score)),
    maxScore,
    message,
    recommendation,
  };
}

// ─── 1. Contact Information Rules (Max 5 Points) ─────────────────────────────
function evalContactRules(r: ParsedResumeData): ATSRuleResult[] {
  const pi: any = r.personalInfo || {};
  const rules: ATSRuleResult[] = [];

  // Name check (1 pt)
  const hasName = Boolean(pi.fullName && pi.fullName.trim().length >= 2);
  rules.push(createRuleResult(
    'contact_name', 'Contact Information', 'critical', hasName,
    hasName ? 1 : 0, 1,
    hasName ? `Full name detected: "${pi.fullName}"` : 'Full name is missing in header.',
    hasName ? null : 'Include your full legal or professional name at the top of your resume.'
  ));

  // Email check (1 pt)
  const hasEmail = Boolean(pi.email && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(pi.email.trim()));
  rules.push(createRuleResult(
    'contact_email', 'Contact Information', 'critical', hasEmail,
    hasEmail ? 1 : 0, 1,
    hasEmail ? `Professional email address detected: "${pi.email}"` : 'No valid email address detected.',
    hasEmail ? null : 'Add a clean, professional email address (e.g. name@domain.com).'
  ));

  // Phone check (1 pt)
  const hasPhone = Boolean(pi.phone && pi.phone.trim().length >= 7);
  rules.push(createRuleResult(
    'contact_phone', 'Contact Information', 'high', hasPhone,
    hasPhone ? 1 : 0, 1,
    hasPhone ? `Phone number detected: "${pi.phone}"` : 'Phone number is missing.',
    hasPhone ? null : 'Add a primary phone number with country/area code.'
  ));

  // LinkedIn check (1 pt)
  const text = getResumeText(r);
  const hasLinkedin = Boolean(pi.linkedin || text.toLowerCase().includes('linkedin.com'));
  rules.push(createRuleResult(
    'contact_linkedin', 'Contact Information', 'medium', hasLinkedin,
    hasLinkedin ? 1 : 0, 1,
    hasLinkedin ? 'LinkedIn profile URL detected.' : 'LinkedIn profile URL not found.',
    hasLinkedin ? null : 'Add your LinkedIn profile URL (e.g. linkedin.com/in/yourname) if you have one.'
  ));

  // GitHub / Portfolio check (1 pt)
  const hasGithubOrPortfolio = Boolean(
    pi.github || pi.website || text.toLowerCase().includes('github.com') || text.toLowerCase().includes('portfolio')
  );
  rules.push(createRuleResult(
    'contact_github_portfolio', 'Contact Information', 'low', hasGithubOrPortfolio,
    hasGithubOrPortfolio ? 1 : 0, 1,
    hasGithubOrPortfolio ? 'GitHub or Portfolio web link detected.' : 'No GitHub or personal portfolio URL detected.',
    hasGithubOrPortfolio ? null : 'Adding a public GitHub or portfolio link can boost technical credibility.'
  ));

  return rules;
}

// ─── 2. Structure & Sections Rules (Max 10 Points) ───────────────────────────
function evalStructureRules(r: ParsedResumeData, resumeType: ResumeType): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const textLower = getResumeText(r).toLowerCase();

  // Section presence check (5 pts)
  const hasSummary = Boolean(r.personalInfo?.summary && r.personalInfo.summary.trim().length >= 10);
  const hasExp = Boolean(r.experiences?.length && r.experiences.length > 0);
  const hasEdu = Boolean(r.education?.length && r.education.length > 0);
  const hasSkills = Boolean(r.skills && r.skills.trim().length >= 5);
  const hasProj = Boolean(r.projects?.length && r.projects.length > 0);

  let structScore = 0;
  if (hasSummary) structScore += 1;
  if (hasEdu) structScore += 1;
  if (hasSkills) structScore += 1;

  if (resumeType === 'fresher') {
    // For Freshers: Projects & Education are prioritized over work experience
    if (hasProj) structScore += 1;
    if (hasExp || (r.certificates && r.certificates.length > 0)) structScore += 1;
  } else {
    // For Experienced candidates: Experience & Projects prioritized
    if (hasExp) structScore += 1;
    if (hasProj || (r.certificates && r.certificates.length > 0)) structScore += 1;
  }

  const passedStruct = structScore >= 4;
  rules.push(createRuleResult(
    'struct_required_sections', 'Resume Structure',
    resumeType === 'fresher' && !hasExp ? 'medium' : 'critical',
    passedStruct,
    structScore, 5,
    passedStruct
      ? `Core resume sections present for a ${resumeType} profile.`
      : `Missing key sections for a ${resumeType} candidate. (${!hasExp && resumeType !== 'fresher' ? 'Missing Experience. ' : ''}${!hasEdu ? 'Missing Education. ' : ''}${!hasSkills ? 'Missing Skills. ' : ''})`,
    passedStruct ? null : `Ensure standard sections (Summary, Skills, ${resumeType === 'fresher' ? 'Projects & Education' : 'Experience & Education'}) are clearly populated.`
  ));

  // Section Order (3 pts)
  // Recommended order: Contact -> Summary -> Skills -> Experience -> Projects -> Education
  const preferred = rulesConfig.preferredSectionOrder || ['contact', 'summary', 'skills', 'experience', 'projects', 'education'];
  const present: string[] = ['contact'];
  if (hasSummary) present.push('summary');
  if (hasSkills) present.push('skills');
  if (hasExp) present.push('experience');
  if (hasProj) present.push('projects');
  if (hasEdu) present.push('education');

  let outOfOrder = 0;
  for (let i = 0; i < present.length - 1; i++) {
    const idxA = preferred.indexOf(present[i]);
    const idxB = preferred.indexOf(present[i + 1]);
    if (idxA !== -1 && idxB !== -1 && idxA > idxB) outOfOrder++;
  }

  const orderScore = Math.max(0, 3 - outOfOrder);
  rules.push(createRuleResult(
    'struct_section_order', 'Resume Structure', 'medium', orderScore === 3,
    orderScore, 3,
    orderScore === 3 ? 'Section ordering matches optimal ATS flow.' : `${outOfOrder} section(s) in non-standard ATS sequence.`,
    orderScore === 3 ? null : 'Reorder sections to standard flow: Contact → Summary → Skills → Experience → Projects → Education.'
  ));

  // Valid Headings & Synonyms (2 pts)
  const synonyms = rulesConfig.sectionNameSynonyms || {};
  let validSynonymHeadings = 0;

  // Check experience synonym
  if (hasExp || Object.values((synonyms as any).experience || {}).some((syn: any) => textLower.includes(String(syn).toLowerCase()))) validSynonymHeadings++;
  // Check education synonym
  if (hasEdu || Object.values((synonyms as any).education || {}).some((syn: any) => textLower.includes(String(syn).toLowerCase()))) validSynonymHeadings++;
  // Check skills synonym
  if (hasSkills || Object.values((synonyms as any).skills || {}).some((syn: any) => textLower.includes(String(syn).toLowerCase()))) validSynonymHeadings++;

  const synonymScore = validSynonymHeadings >= 3 ? 2 : validSynonymHeadings >= 2 ? 1 : 0;
  rules.push(createRuleResult(
    'struct_valid_headings', 'Resume Structure', 'low', synonymScore === 2,
    synonymScore, 2,
    synonymScore === 2 ? 'Standard section headings recognized.' : 'Non-standard headings detected.',
    synonymScore === 2 ? null : 'Use clear, standard section titles like "Work Experience", "Education", and "Technical Skills".'
  ));

  return rules;
}

// ─── 3. Formatting & Layout Reliability Rules (Max 10 Points) ─────────────────
function evalFormattingRules(r: ParsedResumeData): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const textLower = getResumeText(r).toLowerCase();

  // Multi-column layout check (3 pts)
  const hasMultiColumn = textLower.includes('table') && textLower.includes('column');
  rules.push(createRuleResult(
    'fmt_multi_column', 'Formatting & Layout', 'high', !hasMultiColumn,
    !hasMultiColumn ? 3 : 1, 3,
    !hasMultiColumn ? 'Clean linear layout detected.' : 'Multi-column elements detected — may reduce parsing reliability.',
    !hasMultiColumn ? null : 'Use a clean single-column layout. Complex multi-column structures may reduce parsing reliability in older ATS parsers.'
  ));

  // Tables / Text boxes check (3 pts)
  const hasTables = textLower.includes('<table') || textLower.includes('textbox');
  rules.push(createRuleResult(
    'fmt_tables_boxes', 'Formatting & Layout', 'high', !hasTables,
    !hasTables ? 3 : 1, 3,
    !hasTables ? 'No text boxes or nested tables detected.' : 'Tables or text boxes detected — may reduce parsing reliability.',
    !hasTables ? null : 'Avoid embedding core text inside tables or graphical text boxes as content may be skipped by ATS parsers.'
  ));

  // Non-standard symbols / Excessive styling (2 pts)
  const emojiPattern = /[\u{1F300}-\u{1FFFF}]/u;
  const pi: any = r.personalInfo || {};
  const hasEmoji = emojiPattern.test(pi.fullName || '') || emojiPattern.test(pi.jobTitle || '');
  rules.push(createRuleResult(
    'fmt_symbols_styling', 'Formatting & Layout', 'medium', !hasEmoji,
    !hasEmoji ? 2 : 0, 2,
    !hasEmoji ? 'Standard character encoding used.' : 'Decorative emojis or non-standard symbols detected in title/header.',
    !hasEmoji ? null : 'Remove emojis or unusual symbols from your name and job title.'
  ));

  // Header / Footer text check (2 pts)
  const hasHeaderFooterSignal = textLower.includes('page 1 of') || textLower.includes('header') || textLower.includes('footer');
  rules.push(createRuleResult(
    'fmt_header_footer', 'Formatting & Layout', 'medium', !hasHeaderFooterSignal,
    !hasHeaderFooterSignal ? 2 : 1, 2,
    !hasHeaderFooterSignal ? 'Primary contact info located in main body document.' : 'Contact information placed in document header/footer — may reduce parsing reliability.',
    !hasHeaderFooterSignal ? null : 'Ensure contact details reside in the main document body, not header/footer zones where parsers might drop them.'
  ));

  return rules;
}

// ─── 4. Technical & Soft Skills Rules (Max 15 Points) ─────────────────────────
function evalSkillsRules(r: ParsedResumeData): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const rawSkills = r.skills || '';
  const skillList = rawSkills.split(/[,|;\/\n]/).map((s) => s.trim()).filter(Boolean);

  // Skill Count & Presence (5 pts)
  let countScore = 0;
  if (skillList.length >= 8 && skillList.length <= 25) countScore = 5;
  else if (skillList.length >= 5 && skillList.length < 8) countScore = 3;
  else if (skillList.length > 25) countScore = 3; // slightly overcrowded
  else if (skillList.length > 0) countScore = 1;

  rules.push(createRuleResult(
    'skills_presence_count', 'Skills',
    skillList.length === 0 ? 'critical' : skillList.length < 5 ? 'high' : 'medium',
    countScore >= 3,
    countScore, 5,
    skillList.length === 0
      ? 'No technical skills listed.'
      : `Found ${skillList.length} skills listed (${skillList.length >= 8 && skillList.length <= 25 ? 'ideal count: 8–25' : 'consider expanding or focusing'}).`,
    countScore >= 3 ? null : 'Aim for 8–25 core technical skills relevant to your target role.'
  ));

  // Skill Categorization (5 pts)
  const isCategorized = /languages?:|frameworks?:|databases?:|devops:|cloud:|tools?:|frontend:|backend:|technical skills:/i.test(rawSkills);
  rules.push(createRuleResult(
    'skills_categorization', 'Skills', 'high', isCategorized || skillList.length < 5,
    isCategorized ? 5 : skillList.length >= 8 ? 2 : 3, 5,
    isCategorized ? 'Skills are neatly categorized (e.g. Languages | Frameworks | Cloud).' : 'Skills listed as an unformatted flat list.',
    isCategorized ? null : 'Group skills into categories (e.g. Languages: React, TS | Databases: PostgreSQL | Cloud: AWS) for higher ATS parsing accuracy.'
  ));

  // Soft Skills Coverage (3 pts)
  const textLower = getResumeText(r).toLowerCase();
  const softKeywords = rulesConfig.softSkillKeywords || [];
  const foundSoft = softKeywords.filter((kw) => textLower.includes(kw.toLowerCase()));
  const softScore = foundSoft.length >= 3 ? 3 : foundSoft.length >= 1 ? 2 : 0;

  rules.push(createRuleResult(
    'skills_soft_skills', 'Skills', 'low', softScore >= 2,
    softScore, 3,
    foundSoft.length > 0 ? `Detected ${foundSoft.length} soft skill signals (${foundSoft.slice(0, 3).join(', ')}).` : 'No soft skill keywords detected.',
    softScore >= 2 ? null : 'Weave soft skills naturally into your experience bullets (e.g. cross-functional collaboration, mentorship, problem-solving).'
  ));

  // Duplicate Skills Check (2 pts)
  const normalizedList = skillList.map(normalizeTerm);
  const duplicates = normalizedList.filter((item, index) => normalizedList.indexOf(item) !== index);
  const uniqueDuplicates = [...new Set(duplicates)];
  const dupScore = uniqueDuplicates.length === 0 ? 2 : 0;

  rules.push(createRuleResult(
    'skills_duplication', 'Skills', 'medium', dupScore === 2,
    dupScore, 2,
    dupScore === 2 ? 'No duplicate skill entries found.' : `Duplicate skills detected: ${uniqueDuplicates.join(', ')}.`,
    dupScore === 2 ? null : `Remove redundant keyword repeats (e.g. "${uniqueDuplicates[0]}") from the skills section.`
  ));

  return rules;
}

// ─── 5. Work Experience Rules (Max 20 Points) ─────────────────────────────────
function evalExperienceRules(r: ParsedResumeData, resumeType: ResumeType): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const exps = r.experiences || [];

  // Experience Presence (5 pts)
  if (exps.length === 0) {
    const isFresher = resumeType === 'fresher';
    const score = isFresher ? 3 : 0; // Freshers not penalized heavily for missing work experience
    rules.push(createRuleResult(
      'exp_presence', 'Work Experience', isFresher ? 'medium' : 'critical', isFresher,
      score, 5,
      isFresher ? 'No professional work experience listed (Fresher profile detected — projects and education prioritized).' : 'No work experience entries found.',
      isFresher ? 'As a fresher, focus on expanding your academic and personal project bullets.' : 'Add your professional work experience entries.'
    ));
  } else {
    rules.push(createRuleResult(
      'exp_presence', 'Work Experience', 'critical', true,
      5, 5,
      `${exps.length} experience entry/entries found.`,
      null
    ));
  }

  // Entry Completeness (5 pts)
  if (exps.length > 0) {
    let incompleteCount = 0;
    exps.forEach((e) => {
      if (!e.title || !e.company || !e.period || (e.bullets || []).length === 0) {
        incompleteCount++;
      }
    });

    const completeScore = incompleteCount === 0 ? 5 : incompleteCount === 1 ? 3 : 1;
    rules.push(createRuleResult(
      'exp_entry_completeness', 'Work Experience', 'high', completeScore >= 3,
      completeScore, 5,
      incompleteCount === 0 ? 'All experience entries contain title, company, dates, and bullets.' : `${incompleteCount} experience entry/entries missing title, company, dates, or bullets.`,
      completeScore >= 3 ? null : 'Ensure every job entry includes job title, company name, date range, and at least 2–3 achievement bullets.'
    ));
  } else {
    rules.push(createRuleResult(
      'exp_entry_completeness', 'Work Experience', 'medium', resumeType === 'fresher',
      resumeType === 'fresher' ? 3 : 0, 5,
      resumeType === 'fresher' ? 'Fresher profile: project entries used in lieu of formal work experience.' : 'No experience entries to evaluate completeness.',
      null
    ));
  }

  // Action Verbs (4 pts)
  const bullets = getAllBullets(r);
  const strongVerbs = (rulesConfig.strongActionVerbs || []).map((v) => v.toLowerCase());
  const weakVerbs = (rulesConfig.weakActionVerbs || []).map((v) => v.toLowerCase());

  let strongCount = 0;
  let weakCount = 0;
  const weakBulletSamples: string[] = [];

  bullets.forEach((b) => {
    const lower = b.trim().toLowerCase();
    const firstWord = lower.split(/\s+/)[0];
    if (strongVerbs.some((v) => lower.startsWith(v) || firstWord === v)) {
      strongCount++;
    } else if (weakVerbs.some((v) => lower.startsWith(v) || lower.includes(v))) {
      weakCount++;
      if (weakBulletSamples.length < 2) weakBulletSamples.push(b);
    }
  });

  const totalVerbed = strongCount + weakCount;
  const strongRate = totalVerbed > 0 ? strongCount / totalVerbed : 0.5;
  const verbScore = bullets.length === 0 ? 1 : strongRate >= 0.7 ? 4 : strongRate >= 0.4 ? 2 : 1;

  rules.push(createRuleResult(
    'exp_action_verbs', 'Work Experience', 'high', verbScore >= 3,
    verbScore, 4,
    `${strongCount} bullet(s) start with strong action verbs. ${weakCount} bullet(s) use passive/weak openers.`,
    verbScore >= 3 ? null : weakBulletSamples.length > 0
      ? `Replace weak verbs in bullets like "${weakBulletSamples[0].slice(0, 60)}..." with strong verbs (Architected, Engineered, Optimized, Automated).`
      : 'Start every bullet point with a powerful, active action verb.'
  ));

  // STAR Format (4 pts)
  const actionSignatures = rulesConfig.starPatternSignatures?.action || ['implemented', 'developed', 'built', 'created'];
  const resultSignatures = rulesConfig.starPatternSignatures?.result || ['%', 'increased', 'decreased', 'reduced', 'improved', 'achieved'];

  const starBullets = bullets.filter((b) => {
    const lower = b.toLowerCase();
    const hasAct = actionSignatures.some((sig) => lower.includes(sig));
    const hasRes = resultSignatures.some((sig) => lower.includes(sig));
    return hasAct && hasRes;
  });

  const starRate = bullets.length > 0 ? starBullets.length / bullets.length : 0;
  const starScore = bullets.length === 0 ? 1 : starRate >= 0.5 ? 4 : starRate >= 0.25 ? 2 : 1;

  rules.push(createRuleResult(
    'exp_star_format', 'Work Experience', 'medium', starScore >= 3,
    starScore, 4,
    `${starBullets.length}/${bullets.length} bullets follow the STAR pattern (Action + Context + Result).`,
    starScore >= 3 ? null : 'Structure experience bullets as: [Strong Action Verb] + [Context/Task] + [Measurable Result].'
  ));

  // Leadership Signals (2 pts)
  const textLower = getResumeText(r).toLowerCase();
  const leadershipKws = (rulesConfig.leadershipKeywords || []).map((k) => k.toLowerCase());
  const foundLead = leadershipKws.filter((kw) => textLower.includes(kw));
  const leadScore = foundLead.length >= 2 ? 2 : foundLead.length === 1 ? 1 : 0;

  rules.push(createRuleResult(
    'exp_leadership', 'Work Experience', 'low', leadScore >= 1,
    leadScore, 2,
    foundLead.length > 0 ? `Leadership signals detected (${foundLead.slice(0, 3).join(', ')}).` : 'No explicit leadership or ownership signals detected.',
    leadScore >= 1 ? null : 'Highlight ownership, initiative, or mentoring where you genuinely exercised leadership.'
  ));

  return rules;
}

// ─── 6. Projects Rules (Max 10 Points) ────────────────────────────────────────
function evalProjectsRules(r: ParsedResumeData, resumeType: ResumeType): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const projects = r.projects || [];

  // Project Presence (4 pts)
  const hasProjects = projects.length > 0;
  const projPresenceScore = hasProjects ? 4 : resumeType === 'fresher' ? 0 : 2;

  rules.push(createRuleResult(
    'proj_presence', 'Projects', resumeType === 'fresher' && !hasProjects ? 'critical' : 'medium', hasProjects,
    projPresenceScore, 4,
    hasProjects ? `${projects.length} project entry/entries found.` : 'No projects section found.',
    hasProjects ? null : 'Add 2–3 relevant technical projects with tech stack and achievement bullets.'
  ));

  // Project Completeness (3 pts)
  if (hasProjects) {
    let incompleteProj = 0;
    projects.forEach((p) => {
      if (!p.title || (!p.description && (!p.bullets || p.bullets.length === 0)) || !p.techStack || p.techStack.length === 0) {
        incompleteProj++;
      }
    });
    const projCompScore = incompleteProj === 0 ? 3 : 1;

    rules.push(createRuleResult(
      'proj_completeness', 'Projects', 'medium', projCompScore === 3,
      projCompScore, 3,
      incompleteProj === 0 ? 'All projects include title, description/bullets, and tech stack.' : `${incompleteProj} project(s) missing tech stack or description bullets.`,
      projCompScore === 3 ? null : 'Ensure every project lists title, tech stack (e.g. React, Node.js), and 2–3 impact bullets.'
    ));
  } else {
    rules.push(createRuleResult(
      'proj_completeness', 'Projects', 'low', resumeType !== 'fresher',
      resumeType === 'fresher' ? 0 : 2, 3,
      resumeType === 'fresher' ? 'Fresher candidates require project details.' : 'Experienced profile without projects section.',
      null
    ));
  }

  // Project Bullet Quality (3 pts)
  const projBullets = projects.flatMap((p) => p.bullets || []);
  const qualityScore = projBullets.length >= 3 ? 3 : projBullets.length >= 1 ? 2 : hasProjects ? 1 : 0;

  rules.push(createRuleResult(
    'proj_bullet_quality', 'Projects', 'low', qualityScore >= 2,
    qualityScore, 3,
    projBullets.length > 0 ? `${projBullets.length} total project bullet(s) analyzed.` : 'No project bullet points found.',
    qualityScore >= 2 ? null : 'Add 2–3 detailed achievement bullets to each project entry.'
  ));

  return rules;
}

// ─── 7. Education Rules (Max 5 Points) ────────────────────────────────────────
function evalEducationRules(r: ParsedResumeData): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const edu = r.education || [];

  // Education Presence (3 pts)
  const hasEdu = edu.length > 0;
  rules.push(createRuleResult(
    'edu_presence', 'Education', 'critical', hasEdu,
    hasEdu ? 3 : 0, 3,
    hasEdu ? `${edu.length} education entry/entries found.` : 'No education section detected.',
    hasEdu ? null : 'Add your highest education entry with degree title, institution, and graduation year.'
  ));

  // Education Completeness (2 pts)
  if (hasEdu) {
    const isComplete = edu.every((e) => Boolean(e.degree && e.institution && e.period));
    rules.push(createRuleResult(
      'edu_completeness', 'Education', 'high', isComplete,
      isComplete ? 2 : 1, 2,
      isComplete ? 'Degree name, institution, and graduation year present.' : 'Incomplete education details (missing degree, school, or date).',
      isComplete ? null : 'Ensure education entries include degree name, institution, and graduation year.'
    ));
  } else {
    rules.push(createRuleResult(
      'edu_completeness', 'Education', 'medium', false,
      0, 2,
      'No education entries to evaluate.',
      'Include your degree title and university/institution.'
    ));
  }

  return rules;
}

// ─── 8. Content Quality & Metrics Rules (Max 10 Points) ───────────────────────
function evalContentQualityRules(r: ParsedResumeData): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const bullets = getAllBullets(r);

  // Quantified Metrics (5 pts)
  const metricPatterns = (rulesConfig.metricsPatterns || []).map((p) => new RegExp(p, 'i'));
  const bulletsWithMetrics = bullets.filter((b) => metricPatterns.some((p) => p.test(b)));
  const metricRate = bullets.length > 0 ? bulletsWithMetrics.length / bullets.length : 0;
  const metricScore = metricRate >= 0.5 ? 5 : metricRate >= 0.25 ? 3 : bulletsWithMetrics.length > 0 ? 2 : 0;

  rules.push(createRuleResult(
    'content_quantified_metrics', 'Content Quality',
    metricScore <= 1 ? 'high' : 'medium',
    metricScore >= 3,
    metricScore, 5,
    `${bulletsWithMetrics.length}/${bullets.length} bullets contain legitimate measurable outcomes (${Math.round(metricRate * 100)}% metric density).`,
    metricScore >= 3
      ? null
      : 'Consider adding a measurable outcome if you have one (e.g. %, $, user count, time saved). Never invent fake metrics.'
  ));

  // Readability / Bullet Length (3 pts)
  const longBullets = bullets.filter((b) => b.split(/\s+/).length > 35);
  const shortBullets = bullets.filter((b) => b.split(/\s+/).length < 6 && b.trim().length > 0);
  const isReadabilityGood = longBullets.length === 0 && shortBullets.length <= 1;
  const readScore = isReadabilityGood ? 3 : longBullets.length <= 1 ? 2 : 1;

  rules.push(createRuleResult(
    'content_readability', 'Content Quality', 'medium', isReadabilityGood,
    readScore, 3,
    isReadabilityGood ? 'Bullet lengths are optimal (10–30 words).' : `Readability warning: ${longBullets.length} overly long bullet(s) (>35 words) or ${shortBullets.length} overly short bullet(s).`,
    isReadabilityGood ? null : 'Keep bullets between 10 and 30 words for optimal ATS parsing and human readability.'
  ));

  // Grammar & Common Typos (2 pts)
  const text = getResumeText(r);
  const typos = rulesConfig.grammarPatterns?.commonTypos || [];
  const foundTypos: string[] = [];

  typos.forEach(([typo]) => {
    if (text.toLowerCase().includes(typo.toLowerCase())) {
      foundTypos.push(typo.trim());
    }
  });

  const typoScore = foundTypos.length === 0 ? 2 : 0;
  rules.push(createRuleResult(
    'content_grammar_spelling', 'Content Quality', 'medium', typoScore === 2,
    typoScore, 2,
    foundTypos.length === 0 ? 'No common spelling typos detected.' : `Possible spelling typo(s) detected: ${foundTypos.join(', ')}.`,
    typoScore === 2 ? null : `Fix common spelling typos like "${foundTypos[0]}".`
  ));

  return rules;
}

// ─── 9. Completeness & Length Rules (Max 5 Points) ────────────────────────────
function evalCompletenessRules(r: ParsedResumeData, resumeType: ResumeType): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const text = getResumeText(r);
  const wordCount = text.split(/\s+/).filter(Boolean).length;
  const { min, max } = rulesConfig.thresholds?.idealWordCount || { min: 400, max: 800 };

  // Word Count / Page Length (3 pts)
  let lengthScore = 3;
  let lengthMsg = `Resume word count is optimal (${wordCount} words).`;
  let lengthRec: string | null = null;

  if (wordCount < 150) {
    lengthScore = 0;
    lengthMsg = `Resume is very short (${wordCount} words).`;
    lengthRec = 'Expand experience and project bullets with detail from your actual work.';
  } else if (wordCount < min) {
    lengthScore = 2;
    lengthMsg = `Resume is slightly concise (${wordCount} words, target: ${min}–${max}).`;
  } else if (wordCount > max * 1.5) {
    if (resumeType === 'experienced') {
      lengthScore = 2; // Experienced candidates allowed 2 pages without heavy penalty
      lengthMsg = `Resume word count is higher (${wordCount} words). Acceptable for senior candidates (1–2 pages).`;
    } else {
      lengthScore = 1;
      lengthMsg = `Resume word count is high (${wordCount} words). Freshers should target ~1 page.`;
      lengthRec = 'Trim redundant bullets or older coursework to maintain a crisp 1-page profile.';
    }
  }

  rules.push(createRuleResult(
    'comp_word_count_length', 'Completeness & Length', 'medium', lengthScore >= 2,
    lengthScore, 3,
    lengthMsg,
    lengthRec
  ));

  // No Empty Sections (2 pts)
  const emptySections: string[] = [];

  if (r.experiences && r.experiences.length > 0) {
    if (r.experiences.some((e) => !e.bullets || e.bullets.length === 0)) {
      emptySections.push('Experience entries without bullets');
    }
  }

  const noEmptyScore = emptySections.length === 0 ? 2 : 0;
  rules.push(createRuleResult(
    'comp_no_empty_sections', 'Completeness & Length', 'medium', noEmptyScore === 2,
    noEmptyScore, 2,
    noEmptyScore === 2 ? 'All populated sections contain valid content.' : `Empty or incomplete sections found: ${emptySections.join('; ')}.`,
    noEmptyScore === 2 ? null : 'Populate or remove empty sections before submitting.'
  ));

  return rules;
}

// ─── 10. Keyword Quality & Repetition Rules (Max 10 Points) ───────────────────
function evalKeywordRules(r: ParsedResumeData, jobDescription?: string): ATSRuleResult[] {
  const rules: ATSRuleResult[] = [];
  const resumeText = getResumeText(r);

  // General Keyword Density (5 pts)
  const words = (resumeText.match(/\b[a-z][a-z0-9+#./-]{3,}\b/gi) || []);
  const totalWords = words.length;

  if (!jobDescription || jobDescription.trim().length < 20) {
    // General mode without JD: check keyword variety and vocabulary richness
    const uniqueWords = new Set(words.map((w) => w.toLowerCase())).size;
    const varietyRatio = totalWords > 0 ? uniqueWords / totalWords : 0;
    const densityScore = varietyRatio >= 0.4 ? 5 : varietyRatio >= 0.25 ? 3 : 2;

    rules.push(createRuleResult(
      'kw_general_density', 'Keywords & Repetition', 'low', densityScore >= 3,
      densityScore, 5,
      `Vocabulary richness score: ${Math.round(varietyRatio * 100)}% unique terms across ${totalWords} words.`,
      densityScore >= 3 ? null : 'Vary your technical vocabulary and include domain-specific tools.'
    ));
  } else {
    // JD mode: calculate normalized keyword density against target JD
    const jdLower = jobDescription.toLowerCase();
    const jdWords = jdLower.match(/\b[a-z][a-z0-9+#./-]{3,}\b/g) || [];
    const stopWords = new Set(['with', 'that', 'this', 'will', 'have', 'from', 'they', 'your', 'more', 'their', 'been', 'able', 'also', 'into', 'over', 'such', 'both', 'well', 'must', 'some', 'each', 'than', 'then', 'when', 'like', 'very', 'just', 'most', 'for', 'and', 'the', 'in', 'to', 'of', 'a', 'an', 'is', 'are', 'was', 'were']);
    const jdKeyTerms = [...new Set((jdWords as string[]).filter((w) => !stopWords.has(w) && w.length >= 4))].map(normalizeTerm);

    let matchCount = 0;
    jdKeyTerms.forEach((term) => {
      if (textContainsTerm(resumeText, term)) matchCount++;
    });

    const matchRate = jdKeyTerms.length > 0 ? matchCount / jdKeyTerms.length : 0.7;
    const jdDensityScore = matchRate >= 0.6 ? 5 : matchRate >= 0.4 ? 3 : matchRate >= 0.2 ? 2 : 1;

    rules.push(createRuleResult(
      'kw_general_density', 'Keywords & Repetition', 'high', jdDensityScore >= 3,
      jdDensityScore, 5,
      `Matched ${matchCount}/${jdKeyTerms.length} target normalized JD terms (${Math.round(matchRate * 100)}% coverage).`,
      jdDensityScore >= 3 ? null : 'Naturally incorporate missing target JD keywords into existing bullets where you have real experience.'
    ));
  }

  // Keyword Repetition Check (5 pts)
  const freq: Record<string, number> = {};
  const stopWords = new Set(['with', 'that', 'this', 'will', 'have', 'from', 'they', 'your', 'more', 'their', 'been', 'able', 'also', 'into', 'over', 'such', 'both', 'well', 'must', 'some', 'each', 'than', 'then', 'when', 'like', 'very', 'just', 'most', 'using', 'built', 'used', 'and', 'for', 'the', 'in', 'to', 'of', 'a', 'an', 'is', 'are', 'was', 'were', 'work', 'working', 'team', 'experience']);

  words.forEach((w) => {
    const norm = normalizeTerm(w);
    if (!stopWords.has(norm) && norm.length >= 3) {
      freq[norm] = (freq[norm] || 0) + 1;
    }
  });

  const maxRepeatThreshold = rulesConfig.thresholds?.maxRepeatedKeywordCount || 5;
  const overRepeated = Object.entries(freq)
    .filter(([, count]) => count > maxRepeatThreshold)
    .sort((a, b) => b[1] - a[1]);

  const repScore = overRepeated.length === 0 ? 5 : overRepeated.length <= 2 ? 3 : 1;
  rules.push(createRuleResult(
    'kw_repetition_check', 'Keywords & Repetition', 'medium', repScore >= 3,
    repScore, 5,
    overRepeated.length === 0
      ? 'No excessive term repetition detected.'
      : `Term repetition warning: "${overRepeated[0][0]}" appears ${overRepeated[0][1]} times (recommended max: ${maxRepeatThreshold}).`,
    repScore >= 3 ? null : `Reduce repetition of "${overRepeated[0][0]}" (${overRepeated[0][1]}x). Use synonyms to vary phrasing while preserving truthfulness.`
  ));

  return rules;
}

// ─── Separate Job Description Match Engine (Requirement 3 & 20) ────────────────

export function calculateJdMatchBreakdown(
  resumeData: ParsedResumeData,
  jobDescription: string
): JDMatchBreakdown {
  if (!jobDescription || jobDescription.trim().length < 20) {
    return {
      keywordMatch: 0,
      skillMatch: 0,
      jobTitleMatch: 0,
      responsibilityMatch: 0,
      technologyMatch: 0,
      experienceMatch: 0,
      educationMatch: 0,
      semanticRelevance: 0,
      overallJdMatchScore: 0,
    };
  }

  const resumeText = getResumeText(resumeData);
  const jdLower = jobDescription.toLowerCase();

  // 1. Keyword Match (Normalized)
  const jdWords = jdLower.match(/\b[a-z][a-z0-9+#./-]{3,}\b/g) || [];
  const stopWords = new Set(['with', 'that', 'this', 'will', 'have', 'from', 'they', 'your', 'more', 'their', 'been', 'able', 'also', 'into', 'over', 'such', 'both', 'well', 'must', 'some', 'each', 'than', 'then', 'when', 'like', 'very', 'just', 'most', 'for', 'and', 'the', 'in', 'to', 'of', 'a', 'an', 'is', 'are', 'was', 'were', 'able', 'need']);
  const uniqueJdTerms = [...new Set((jdWords as string[]).filter((w) => !stopWords.has(w) && w.length >= 4))];

  let kwMatches = 0;
  uniqueJdTerms.forEach((t) => {
    if (textContainsTerm(resumeText, t)) kwMatches++;
  });
  const keywordMatch = uniqueJdTerms.length > 0 ? clamp(Math.round((kwMatches / uniqueJdTerms.length) * 100)) : 70;

  // 2. Technology Match (Normalized tech stack)
  const techTerms = ['react', 'typescript', 'javascript', 'node.js', 'python', 'postgresql', 'aws', 'docker', 'kubernetes', 'ci/cd', 'tailwind css', 'express', 'next.js', 'redis', 'graphql', 'mongodb', 'jest', 'playwright'];
  const jdTech = techTerms.filter((t) => textContainsTerm(jobDescription, t));
  const resumeTechMatched = jdTech.filter((t) => textContainsTerm(resumeText, t));
  const technologyMatch = jdTech.length > 0 ? clamp(Math.round((resumeTechMatched.length / jdTech.length) * 100)) : 75;

  // 3. Skill Match
  const skillMatch = clamp(Math.round(keywordMatch * 0.6 + technologyMatch * 0.4));

  // 4. Job Title Match
  const pi: any = resumeData.personalInfo || {};
  const candTitle = (pi.jobTitle || '').toLowerCase();
  const jdTitleMatch = jdLower.match(/(senior|lead|staff|principal|junior|mid)?\s*(full\s*stack|frontend|backend|software|devops|data|cloud)\s*(engineer|developer|architect|lead)/i);
  const expectedTitle = jdTitleMatch ? jdTitleMatch[0].toLowerCase() : '';

  let jobTitleMatch = 60;
  if (expectedTitle && candTitle) {
    if (areTermsEquivalent(candTitle, expectedTitle) || candTitle.includes(expectedTitle) || expectedTitle.includes(candTitle)) {
      jobTitleMatch = 95;
    } else {
      const candNorm = normalizeTerm(candTitle);
      const expNorm = normalizeTerm(expectedTitle);
      if (candNorm.split(' ').some((word) => expNorm.includes(word))) jobTitleMatch = 80;
    }
  }

  // 5. Responsibility Match (Bullet overlap with JD action phrases)
  const bullets = getAllBullets(resumeData);
  const jdActions = ['build', 'design', 'develop', 'architect', 'lead', 'manage', 'scale', 'optimize', 'deploy', 'integrate'];
  const matchedActions = jdActions.filter((act) =>
    bullets.some((b) => b.toLowerCase().includes(act)) && jdLower.includes(act)
  );
  const responsibilityMatch = clamp(Math.round((matchedActions.length / Math.max(1, jdActions.filter((a) => jdLower.includes(a)).length)) * 100));

  // 6. Experience Level Match
  const candExps = resumeData.experiences || [];
  const reqYearsMatch = jdLower.match(/(\d+)\+?\s*years/i);
  const reqYears = reqYearsMatch ? parseInt(reqYearsMatch[1]) : 3;

  let experienceMatch = 80;
  if (resumeData.resumeType === 'fresher' && reqYears > 3) {
    experienceMatch = 50;
  } else if (candExps.length >= Math.min(3, reqYears)) {
    experienceMatch = 90;
  }

  // 7. Education Match
  const hasEdu = Boolean(resumeData.education?.length);
  const reqDegree = /bachelor|master|degree|computer science|bs|ms/i.test(jdLower);
  const educationMatch = hasEdu ? 95 : reqDegree ? 40 : 75;

  // 8. Semantic Relevance
  const semanticRelevance = clamp(Math.round(
    keywordMatch * 0.3 +
    technologyMatch * 0.25 +
    jobTitleMatch * 0.2 +
    responsibilityMatch * 0.15 +
    experienceMatch * 0.1
  ));

  // Overall JD Match Score (Weighted sum of breakdown components)
  const overallJdMatchScore = clamp(Math.round(
    keywordMatch * 0.25 +
    skillMatch * 0.20 +
    technologyMatch * 0.20 +
    jobTitleMatch * 0.15 +
    responsibilityMatch * 0.10 +
    experienceMatch * 0.05 +
    educationMatch * 0.05
  ));

  return {
    keywordMatch,
    skillMatch,
    jobTitleMatch,
    responsibilityMatch,
    technologyMatch,
    experienceMatch,
    educationMatch,
    semanticRelevance,
    overallJdMatchScore,
  };
}

// ─── Missing Keyword Categorizer (Requirement 5) ─────────────────────────────

export function extractCategorizedMissingKeywords(
  resumeData: ParsedResumeData,
  jobDescription?: string
): CategorizedMissingKeyword[] {
  if (!jobDescription || jobDescription.trim().length < 20) return [];

  const resumeText = getResumeText(resumeData);
  const jdLower = jobDescription.toLowerCase();

  const TECH_CATEGORIES: Record<string, { category: string; terms: string[] }> = {
    languages: {
      category: 'Programming Language',
      terms: ['typescript', 'javascript', 'python', 'java', 'go', 'golang', 'rust', 'c++', 'c#', 'ruby', 'php', 'swift', 'kotlin', 'sql'],
    },
    frameworks: {
      category: 'Framework / Library',
      terms: ['react', 'next.js', 'express', 'vue', 'angular', 'svelte', 'django', 'flask', 'fastapi', 'spring boot', 'graphql', 'redux', 'zustand', 'tailwind css'],
    },
    databases: {
      category: 'Database',
      terms: ['postgresql', 'mongodb', 'redis', 'mysql', 'sqlite', 'dynamodb', 'elasticsearch', 'supabase'],
    },
    cloud: {
      category: 'Cloud Infrastructure',
      terms: ['aws', 'gcp', 'azure', 'vercel', 'netlify', 'heroku', 'docker', 'kubernetes'],
    },
    devops: {
      category: 'DevOps / Tooling',
      terms: ['ci/cd', 'github actions', 'terraform', 'jenkins', 'git', 'vite', 'webpack'],
    },
    testing: {
      category: 'Testing Framework',
      terms: ['jest', 'playwright', 'cypress', 'vitest', 'mocha'],
    },
  };

  const missing: CategorizedMissingKeyword[] = [];

  for (const group of Object.values(TECH_CATEGORIES)) {
    for (const term of group.terms) {
      if (textContainsTerm(jobDescription, term) && !textContainsTerm(resumeText, term)) {
        // Calculate frequency in JD
        const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const freq = (jdLower.match(new RegExp(`\\b${escaped}\\b`, 'gi')) || []).length || 1;
        const importance = freq >= 3 ? 'Critical' : freq >= 2 ? 'High' : 'Medium';

        missing.push({
          keyword: term.charAt(0).toUpperCase() + term.slice(1),
          category: group.category,
          importance,
          found: false,
          recommended: true,
          frequency: freq,
          estimatedGain: Math.min(6, freq * 2),
        });
      }
    }
  }

  return missing.sort((a, b) => b.frequency - a.frequency).slice(0, 15);
}

// ─── Main Engine Entrypoint ───────────────────────────────────────────────────

export interface ATSEngineOptions {
  jobDescription?: string;
}

/**
 * Analyzes a resume against deterministic ATS rules.
 *
 * @param resumeData - Parsed candidate resume data
 * @param options - Optional target job description for JD-Match evaluation
 * @returns ATSFullReport containing deterministic scores, rule breakdowns, and fixes
 */
export function analyzeResume(
  resumeData: ParsedResumeData,
  options: ATSEngineOptions = {}
): ATSFullReport {
  const jd = options.jobDescription;
  const resumeType: ResumeType = resumeData.resumeType || 'experienced';

  // Evaluate all 10 core category rule groups
  const contactRules = evalContactRules(resumeData);
  const structRules = evalStructureRules(resumeData, resumeType);
  const fmtRules = evalFormattingRules(resumeData);
  const skillsRules = evalSkillsRules(resumeData);
  const expRules = evalExperienceRules(resumeData, resumeType);
  const projRules = evalProjectsRules(resumeData, resumeType);
  const eduRules = evalEducationRules(resumeData);
  const contentRules = evalContentQualityRules(resumeData);
  const compRules = evalCompletenessRules(resumeData, resumeType);
  const kwRules = evalKeywordRules(resumeData, jd);

  const allRules: ATSRuleResult[] = [
    ...contactRules,
    ...structRules,
    ...fmtRules,
    ...skillsRules,
    ...expRules,
    ...projRules,
    ...eduRules,
    ...contentRules,
    ...compRules,
    ...kwRules,
  ];

  // Sum total points earned and max points across all rules
  const totalEarned = allRules.reduce((sum, r) => sum + r.score, 0);
  const totalMax = allRules.reduce((sum, r) => sum + r.maxScore, 0); // Always 100 points!

  // Final ATS Score is 100% deterministic (scaled to 100)
  const finalScore = clamp(Math.round((totalEarned / totalMax) * 100));

  // Determine score label
  let scoreLabel = 'Needs Work';
  if (finalScore >= 85) scoreLabel = 'Excellent';
  else if (finalScore >= 70) scoreLabel = 'Good';
  else if (finalScore >= 50) scoreLabel = 'Average';

  // Build category results record
  const mapGroupToCategoryResult = (
    key: ATSCategoryKey,
    label: string,
    groupRules: ATSRuleResult[]
  ): ATSCategoryResult => {
    const groupEarned = groupRules.reduce((sum, r) => sum + r.score, 0);
    const groupMax = groupRules.reduce((sum, r) => sum + r.maxScore, 0);
    const groupScore = clamp(Math.round((groupEarned / groupMax) * 100));
    const passed = groupScore >= 70;

    const failedRule = groupRules.find((r) => !r.passed);
    const reason = failedRule ? failedRule.message : groupRules[0]?.message || `${label} rules passed.`;
    const fixSuggestion = failedRule?.recommendation || `Maintain high standard for ${label.toLowerCase()}.`;

    let priority: ATSPriority = 'Low';
    if (groupScore < 40) priority = 'Critical';
    else if (groupScore < 60) priority = 'High';
    else if (groupScore < 80) priority = 'Medium';

    const estimatedAtsGain = clamp(Math.round(((100 - groupScore) / 100) * groupMax), 1, 15);

    return {
      key,
      label,
      score: groupScore,
      pointsEarned: groupEarned,
      pointsMax: groupMax,
      reason,
      fixSuggestion,
      priority,
      estimatedAtsGain,
      passed,
      rules: groupRules,
    };
  };

  const categoriesRecord: Record<ATSCategoryKey, ATSCategoryResult> = {
    contactInfo: mapGroupToCategoryResult('contactInfo', 'Contact Information', contactRules),
    sections: mapGroupToCategoryResult('sections', 'Resume Structure', structRules),
    sectionOrder: mapGroupToCategoryResult('sectionOrder', 'Section Order', structRules.slice(1, 2)),
    formatting: mapGroupToCategoryResult('formatting', 'Formatting & Layout', fmtRules),
    hardSkills: mapGroupToCategoryResult('hardSkills', 'Hard Skills', skillsRules.slice(0, 2)),
    softSkills: mapGroupToCategoryResult('softSkills', 'Soft Skills', skillsRules.slice(2, 3)),
    experience: mapGroupToCategoryResult('experience', 'Work Experience', expRules),
    projects: mapGroupToCategoryResult('projects', 'Projects', projRules),
    education: mapGroupToCategoryResult('education', 'Education', eduRules),
    metrics: mapGroupToCategoryResult('metrics', 'Quantified Metrics', contentRules.slice(0, 1)),
    starFormat: mapGroupToCategoryResult('starFormat', 'STAR Format', expRules.filter((r) => r.id === 'exp_star_format')),
    actionVerbs: mapGroupToCategoryResult('actionVerbs', 'Action Verbs', expRules.filter((r) => r.id === 'exp_action_verbs')),
    leadership: mapGroupToCategoryResult('leadership', 'Leadership Signals', expRules.filter((r) => r.id === 'exp_leadership')),
    readability: mapGroupToCategoryResult('readability', 'Readability', contentRules.slice(1, 2)),
    bulletQuality: mapGroupToCategoryResult('bulletQuality', 'Bullet Quality', contentRules.slice(1, 3)),
    length: mapGroupToCategoryResult('length', 'Resume Length', compRules.slice(0, 1)),
    title: mapGroupToCategoryResult('title', 'Title & Headline', contactRules.slice(0, 1)),
    github: mapGroupToCategoryResult('github', 'GitHub Profile', contactRules.filter((r) => r.id === 'contact_github_portfolio')),
    portfolio: mapGroupToCategoryResult('portfolio', 'Portfolio / Website', contactRules.filter((r) => r.id === 'contact_github_portfolio')),
    linkedin: mapGroupToCategoryResult('linkedin', 'LinkedIn Profile', contactRules.filter((r) => r.id === 'contact_linkedin')),
    certificates: mapGroupToCategoryResult('certificates', 'Certifications', structRules),
    achievements: mapGroupToCategoryResult('achievements', 'Achievements', contentRules),
    missingSkills: mapGroupToCategoryResult('missingSkills', 'Missing Skills (JD)', kwRules),
    repeatedKeywords: mapGroupToCategoryResult('repeatedKeywords', 'Repeated Keywords', kwRules.filter((r) => r.id === 'kw_repetition_check')),
    keywordDensity: mapGroupToCategoryResult('keywordDensity', 'Keyword Density', kwRules.filter((r) => r.id === 'kw_general_density')),
    keywords: mapGroupToCategoryResult('keywords', 'Keyword Optimization', kwRules),
    dateConsistency: mapGroupToCategoryResult('dateConsistency', 'Date Consistency', compRules),
    grammarTypos: mapGroupToCategoryResult('grammarTypos', 'Grammar & Typos', contentRules.filter((r) => r.id === 'content_grammar_spelling')),
  };

  // Extract missing keywords
  const categorizedMissing = extractCategorizedMissingKeywords(resumeData, jd);
  const missingKeywords = categorizedMissing.map((m) => ({
    keyword: m.keyword,
    category: m.category,
    importance: m.importance,
    found: m.found,
    recommended: m.recommended,
    frequency: m.frequency,
    estimatedGain: m.estimatedGain,
  }));

  // Repeated keywords
  const resumeText = getResumeText(resumeData);
  const words = resumeText.match(/\b[a-z][a-z0-9+#./-]{3,}\b/gi) || [];
  const freq: Record<string, number> = {};
  const stopWords = new Set(['with', 'that', 'this', 'will', 'have', 'from', 'they', 'your', 'more', 'their', 'been', 'able', 'also', 'into', 'over', 'such', 'both', 'well', 'must', 'some', 'each', 'than', 'then', 'when', 'like', 'very', 'just', 'most', 'using', 'built', 'used', 'and', 'for', 'the', 'in', 'to', 'of', 'a', 'an', 'is', 'are', 'was', 'were']);
  words.forEach((w) => {
    const norm = normalizeTerm(w);
    if (!stopWords.has(norm)) freq[norm] = (freq[norm] || 0) + 1;
  });

  const repeatedKeywords = Object.entries(freq)
    .filter(([, count]) => count > 4)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([keyword, count]) => ({ keyword, count }));

  // Top fixes from failed rules
  const failedCategories = Object.values(categoriesRecord)
    .filter((c) => !c.passed)
    .sort((a, b) => b.estimatedAtsGain - a.estimatedAtsGain)
    .slice(0, 5);

  // Calculate separate JD Match Breakdown if JD is present
  const jdMatchBreakdown = jd ? calculateJdMatchBreakdown(resumeData, jd) : undefined;

  return {
    finalScore,
    scoreLabel,
    categories: categoriesRecord,
    ruleResults: allRules,
    scoringBreakdown: {
      totalPointsEarned: totalEarned,
      totalMaxPoints: totalMax,
    },
    missingKeywords,
    categorizedMissingKeywords: categorizedMissing,
    repeatedKeywords,
    topFixes: failedCategories,
    jdMatchBreakdown,
    analysisSource: 'client',
    analyzedAt: new Date().toISOString(),
  };
}

export const atsEngine = {
  analyzeResume,
  normalizeTerm,
  areTermsEquivalent,
  textContainsTerm,
  calculateJdMatchBreakdown,
  extractCategorizedMissingKeywords,
};

export default atsEngine;
